/**
 * Socle Symfony2 API
 * Documented API for Socle symfony2
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface User {
    username: string;

    firstname: string;

    lastname: string;

    password: string;

    email?: string;

    dateOfBirth?: string;

    gender?: User.GenderEnum;

    phone?: string;

    roles?: Array<models.Role>;

    id?:string;

}
export namespace User {
    export enum GenderEnum {
        Male = <any> 'male',
        Female = <any> 'female'
    }
}
