/**
 * Socle Symfony2 API
 * Documented API for Socle symfony2
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface WidgetUsers {
  name?: string;
  id?: string;
  position?: string;

  etat?: WidgetUsers.EtatEnum;

  category?: string;

  typeChart?: string;

  id_user: string;

}
export namespace WidgetUsers {
  export enum EtatEnum {
    Open = <any> 'open',
    Close = <any> 'close'
  }
}
